# Site settings
author: Sherry Martin
title: Full Stack Developer
header-img: img/home-bg.png
email: sm674@cornell.edu
copyright_name: Sherry Martin
description: > # this means to ignore newlines until "baseurl:"
  Interdisciplinary mindset 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SMartinSci

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
